<?php
  // FILL IN YOUR DATABASE INFORMATION HERE
  
  DB_HOST = "";
  DB_USERNAME = "";
  DB_PASSWORD = "";
  DB_DATABASE = "";
  
  $db = mysqli_connect(DB_HOST, DB_USERNAME, DB_PASSWORD, DB_DATABASE);
?>
